services:
  gameinfoservice:  
    build:    
      context: ./server/services/gameInfoService # Correct the path if necessary 
      dockerfile: Dockerfile 
    ports: 
      - 5001:5001
    environment:
        - GAMES_API_BASE_DOMAIN=http://127.0.0.1:5001
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  playerinfoservice:
    build:
      context: ./server/services/playerInfoService
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    environment:
        - PLAYERS_API_BASE_DOMAIN=http://127.0.0.1:5002
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  server:      
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
        - SERVER_API_BASE_DOMAIN=http://127.0.0.1:5000
    depends_on:
      - gameinfoservice
      - playerinfoservice
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  steamviewer:      
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - server
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json