services:
  gameinfoservice:
    build:
      context: ../steam-viewer-games-service/ # Correct the path if necessary 
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - GAMES_API_BASE_DOMAIN=http://127.0.0.1:5001
    develop:
      watch:
        - action: sync
          path: ../steam-viewer-games-service/
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  playerinfoservice:
    env_file: .env
    build:
      context: ../steam-viewer-player-service/
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    environment:
      - PLAYERS_API_BASE_DOMAIN=http://127.0.0.1:5002
    develop:
      watch:
        - action: sync
          path: ../steam-viewer-player-service/
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  server:
    build:
      context: ../steam-viewer-backend/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - SERVER_API_BASE_DOMAIN=http://127.0.0.1:5000
      - SECRET_API_KEY='john'
    depends_on:
      - gameinfoservice
      - playerinfoservice
    develop:
      watch:
        - action: sync
          path: ../steam-viewer-backend/
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  steamviewer:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - server
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
