FROM node:19
ENV API_KEY=87CE6665185863997A652C536B84B4FC
RUN npm install --global nodemon
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5000
CMD ["./node_modules/.bin/nodemon", "server.js"]